### ISSUE TITLE
Conflict layers in Spatialite working copy are not added to the project

### ISSUE THREAD

**Issue by Roel** [Oslandia/qgis-versioning#14]
The conflict layers created in Spatialite working copies are not added to the QGis project (an errormessage is shown briefly). You can still add them manually by connecting to the Spatialite db and ticking the 'Also list tables with no geometry' box. They are then added as flat tables without geometry.

Source of the issue seems to be the call to the RecoverGeometryColumn function (versioning_base line 572), which fails in my Spatialite db: (this is on Spatialite version 4.1.1 and 4.3.0)

> spatialite> SELECT RecoverGeometryColumn('allepercelen_conflicts', 'GEOMETRY', (SELECT srid FROM geometry_columns WHERE f_table_name='allepercelen'), (SELECT geometry_type FROM geometry_columns WHERE f_table_name='allepercelen'), 'XY');
> RecoverGeometryColumn() error: argument 4 [geometry_type] is not of the String type

Some searching reveals that the geometry_type is stored as an integer value since Spatialite [v4.0.0](https://www.gaia-gis.it/fossil/libspatialite/wiki?name=switching-to-4.0), but the RecoverGeometryColumn function still expects a string.

**Comment by vmora** [comment]
Is it possible to add a unit test that reproduces the issue ?

**Comment by Roel** [comment]
I've never made such a test before, but I'll try to make something based on the existing examples.

**Comment by ymoisan** [comment]
@Roel : it seems your PR was integrated on Aug 13, 2015 (#15).  I personally have always seen conflict layers loaded in QGIS, but my tests were done after Aug 13 so with the PR included.  Are there edge cases I haven't seen or is this issue fixed ?
