### ISSUE TITLE
Support for PostGIS databases using non-'public' schema

### ISSUE THREAD

**Issue by Roel** [Oslandia/qgis-versioning#17]
PostGIS databases using a schema other than 'public' for their functions and tables are currently unsupported due to the use of the 'active_schema' option in ogr2ogr.

**Comment by vmora** [comment]
@Roel can you confirm that it's fixed in recent plugins version and close ?

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/qgis/qgis-versioning/-/issues/17
