### ISSUE TITLE
Mac OS X - checkout with SpatiaLite...

### ISSUE THREAD

**Issue by gignacnic** [Oslandia/qgis-versioning#19]
I cannot checkout with my current QGIS 2.10 (same for QGIS 2.8) in SpatiaLite format on my Mac OS X Yosemite 10.10.4, PostGIS checkout is fine.
See the details below. I have installed requirement put here:http://www.kyngchaos.com/software/qgis

Any idea what can cause this problem?

Traceback (most recent call last):
  File "/Users/xxxxx/.qgis2/python/plugins/qgis_versioning/versioning.py", line 578, in checkout
    tables_for_conninfo, filename )
  File "/Users/xxxxx/.qgis2/python/plugins/qgis_versioning/versioning_base.py", line 273, in checkout
    "AND "+branch+"_rev_begin IS NOT NULL")
  File "/Users/xxxxxx/.qgis2/python/plugins/qgis_versioning/versioning_base.py", line 63, in execute
    self.cur.execute( sql )
OperationalError: near "FROM": syntax error

Version de Python :
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]

Version de QGIS :
2.10.1-Pisa Pisa, 

Chemin vers Python : ['/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing', '/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/xxxxx/.qgis2/python', u'/Users/annic/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/Applications/QGIS.app/Contents/MacOS/grass/etc/python', '/', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', u'/Users/xxxxx/.qgis2//python', '/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools']

**Comment by vmora** [comment]
Can you set the verbose option in the cursor decorator (Db instance) to see the complete sql statement ?

**Comment by gignacnic** [comment]
After investigating, I have found it was a system configuration of GDAL that needed to be done on my  Mac. My problem (in debug mode in QGIS I had this: sh: ogr2ogr: command not found) was fixed by this config:
export PATH=/Library/Frameworks/GDAL.framework/Programs:$PATH
I found it while using this config steps of GDAL on Mac (not the formal one of the KyngChaos web site) : https://sites.google.com/site/eospansite/installinggdalonmacosx

However, when I was using the basic import-export tools in QGIS (which should use ogr2ogr also? and config system) I did not have any problem to transform format to format such as SpatiaLite, even without this fix configuration system. Maybe this configuration system (check list) needs to be more documented over the plugin.

**Comment by gignacnic** [comment]
How to make it work with Spatial Checkout and ogr2ogr for Mac OS, here are the command to use in the Terminal in Mac, first:
export PATH=/Library/Frameworks/GDAL.framework/Programs:$PATH
then:
/Applications/Qgis.app/Contents/MacOS/Qgis

**Comment by vmora** [comment]
@gignacnic we could add os.environ["PATH"] +=  ":/Library/Frameworks/GDAL.framework/Programs" 
at the start of versionning when the os is Mac.

Maybe test if it's already in there first.

**Comment by gignacnic** [comment]
ok, it works, I will send it into the PR#60.

**Comment by vmora** [comment]
@gignacnic nope, you should base your branche on my #57 since #60 is not going to be merged (it's been merged manually in #57)
