### ISSUE TITLE
Features appearing twice in Spatialite working copy

### ISSUE THREAD

**Issue by Roel** [Oslandia/qgis-versioning#25]
I notice features appearing multiple times in Spatialite working copies when synchronising data between multiple clients. The PostGIS master table and views are not affected, the problem exists only in the working copies on the clients.

Furthermore it appears to occur only with features edited by other users and when synchronising multiple revisions at once.

This leads me to believe the diff applied on update is incomplete. It is calculated as follows:

```
        pcur.execute( "CREATE TABLE "+diff_schema+"."+table+"_diff AS "
                "SELECT "+cols+geom+" "
                "FROM "+table_schema+"."+table+" "
                "WHERE "+branch+"_rev_end = "+str(rev)+" "
                "OR "+branch+"_rev_begin > "+str(rev))
```

Imagine the following situation (PostGIS mastertable):

```
ogc_fid | feature | rev_begin | rev_end
--------+---------+-----------+--------
1       | 1       | 1         | 1
2       | 1       | 2         | NULL
3       | 2       | 1         | 3
4       | 2       | 4         | NULL
```

When updating from revision 1 to 5 (f.ex.), line 3 is not included in the diff (since rev_end = 3, not 1). When this feature was not modified in the current client the rev_end is NULL (initially set). The diff only transfers line 4, which is added to the mastertable on the client. The view clientside now shows two versions for feature 2: both rev_begin=1 and rev_begin=4 match the condition rev_end is null.

I think this can be fixed changing the diff statement to include records where rev_end >= rev instead of strictly rev_end = rev? Is this correct or am I missing something?

**Comment by ymoisan** [comment]
I have experienced the same behaviour : GISeHealth#19

**Comment by vmora** [comment]
@ymoisan, @Roel it would be nice to have a test case for that.

**Comment by ymoisan** [comment]
@vmora : see comment today at GISeHealth#19

**Comment by ymoisan** [comment]
"changing the diff statement to include records where rev_end >= rev instead of strictly rev_end = rev? "
the code shows ">=" in *update* and "=" in *pg_update*.

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
