### ISSUE TITLE
Please add it to standard repo

### ISSUE THREAD

**Issue by pcav** [Oslandia/qgis-versioning#3]
Thanks

**Comment by gignacnic** [comment]
@vmora  this has not been fixed, now that all formal plugin release are pushed it the formal QGIS plugin repo?

**Comment by vmora** [comment]
@gignacnic I'm not sure I understand the question.

**Comment by gignacnic** [comment]
This issue should not be closed?

**Comment by vmora** [comment]
Yes, you are right.
