### ISSUE TITLE
No author in revisions table when creating a branch

### ISSUE THREAD

**Issue by ymoisan** [Oslandia/qgis-versioning#38]
Creating a new branch adds a new record to the revisions table, but without an author : 

![no-author](https://cloud.githubusercontent.com/assets/7468595/12950052/340e2896-cfd9-11e5-9971-71d1e322a09d.png)

**Comment by SebastienPeillet** [comment]
> Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
