### ISSUE TITLE
Spatialite checkout won't update after branch creation

### ISSUE THREAD

**Issue by ymoisan** [Oslandia/qgis-versioning#39]
Take an existing spatialite working copy (checkout of TRUNK) at revision X.  Create a new branch (rev X + 1).

Trying to update the working copy to rev = X + 1 will return an "already up to date message".  Doing another spatialite checkout will however create a sqlite file with the right revisions number (X + 1) so in effect the user will have two identical spatialite checkouts but with different revision numbers.

Committing edits from the newly created spatialite checkout  correctly creates revision X + 2 (trunk).  Then it is possible to update the problematic working copy from X to X + 2.

I did nor try committing changes in the new branch to see if the working copy that existed prior to branch creation was still denied updating.

**Comment by ymoisan** [comment]
A test this morning indicates a little more complicated behaviour.  I successfully updated a very old working copy that was 16 revisions behind HEAD even though there have been new branches created in one of those revisions.

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
