### ISSUE TITLE
python error when clicking on group

### ISSUE THREAD

**Issue by gioman** [Oslandia/qgis-versioning#4]
I just noticed that in a project with groups not containing postgis layers I get the following

Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/qgis-versioning/versioning.py", line 220, in on_legend_click
    assert( selection_type )
AssertionError

**Comment by ymoisan** [comment]
Or an error message could be generated or better the "V" could be replaced by some sort of "non-versionable" icon (thereby not interrupting the user and just showing the state of the group).  If a user creates a group of layers coming e.g. from shapefiles, clicking on the group triggers the assert error (tested on the latest plugin code).

**Comment by vmora** [comment]
@ymoisan, this is what I wanted to achieve, but my logic was flowed because I forgot to test that there was a database in layer source. Should be fixed now. Thanks for reporting.

**Comment by ymoisan** [comment]
Head revision : d30787e (your recent commit)

The plugin menu shows the text "Not versionable" instead of the assert error

Thanx !
