### ISSUE TITLE
Infotext in plugin issues

### ISSUE THREAD

**Issue by ymoisan** [Oslandia/qgis-versioning#40]
The infotext displayed on the left of the plugin menu shows inconsistencies.
1. Deleting a group in legend does not trigger an update in the infotext

To reproduce : 
- add a working copy and click on the group : text info on the left of the plugin menu displays correctly
- remove layer group : text info remains unchanged (still showing the previous SL filename or DB info for pg checkout)

The only way the user can get the text updated is by clicking on the legend; legend.clicked is the only signal handled in the plugin.

Solution : I tried looking quickly for a "group[item]Removed" type of signal but to no avail.  LegendInterface seems to have that signal, but connecting to the on_legend_click member 

```
self.iface.legendInterface().itemRemoved.connect(self.on_legend_click)
```

triggers an exception.
1. A newly created "full mode" revision group (view button, "Compare selected revisions" unchecked) brings a "Versioning : unversioned schema" infotext
2. A newly created "diff mode" revision group (view button, "Compare selected revisions" checked) brings a "Versioning : not versionable" infotext

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
