### ISSUE TITLE
Customization : override some plugin default settings

### ISSUE THREAD

**Issue by ymoisan** [Oslandia/qgis-versioning#43]
There is a need to add organization-specific items to customize the plugin installation.  Two such items for the versioning plugin are : 
- disable the use of branches
- provide a different url for the documentation

Second url below says "global settings ... provided directly by Qt framework by the means of QSettings class. By default, this class stores settings in system’s “native” way of storing settings, that is — registry (on Windows), .plist file (on Mac OS X) or .ini file (on Unix)." so it would be a matter of defining those settings for the plugin, have default values for those settings and those would be writtent at the right location in users computers.

Useful urls : 
- http://documentation.qgis.org/2.8/de/docs/pyqgis_developer_cookbook/settings.html
- http://gis.stackexchange.com/questions/80025/how-do-i-access-qgis-program-settings-programmatically

**Comment by ymoisan** [comment]
Question : what if the user installing the plugin on Windows does not have write access to the registry ?  Can we have a default value in the plugin runtime then until sys admins fill in values for those settings as registry keys ?

**Comment by vmora** [comment]
1 Only the one setting up qgis for health will need writting
2 Normally QSetting will deal with those kind of problems (to be tested) because qgis makes use of those, and there is no problem that I know about.

**Comment by ymoisan** [comment]
Thanx.  To avoid problems for non admin Windows users, I would check in the plugin if a value is set.  If not, I'd give it the default (hardcoded in Python).  Else I'd take whatever QSettingsvalue() returns.

**Comment by vmora** [comment]
The `value(name, default)` is meant for that, no need to check, it will return the default if value is not defined.

**Comment by ymoisan** [comment]
Excellent, thanx !

**Comment by ymoisan** [comment]
Two (2) QSettings implemented : 04e66e4

    'qgis-versioning/use-branches'
branches disabled if value is "False" or "false" (booleans cast to str to make sure we catch those too); else enabled

    'qgis-versioning/help-url'
any well-formed url, else the default RTD site.

Pretty simple.  Works whether system wide (e.g. registry keys) settings exist or not.  Tested on Ubuntu and Windows 10.

@vmora : does that look OK to you ?  If so will add docs for that and I should submit a PR tomorrow.  

The general idea is that customization is *possible*, not compulsory.  Therefore I have not written a short one-off Python script to set the variables yet (nor did I add any code in historize to set those QSettings).  I think just instructing users how  they can customize those two settings in the Python command prompt in QGIS is enough.  Active Directory administrators will like the fact they can apply organization wide settings if they wish.  See docx below for an example in Windows.

[hkey-qgis-versioning-before-after-1.docx](https://github.com/Oslandia/qgis-versioning/files/145209/hkey-qgis-versioning-before-after-1.docx)

**Comment by ymoisan** [comment]
Added documentation : 8424e4c

**Comment by vmora** [comment]
@ymoisan from the discussion, I think we can close that, can you confirm ?

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
