### ISSUE TITLE
Syntax Error in Delete Trigger in PostGIS checkout

### ISSUE THREAD

**Issue by eg-novelt** [Oslandia/qgis-versioning#45]
To reproduce the problem, create a PostGIS checkout, then try to delete some geometries.  There will be a syntax error in the delete trigger.

The problem is here: 

https://github.com/Oslandia/qgis-versioning/blob/master/versioning_base.py#L1479

The hardcoded schema in the code "epanet" does not exist.  Seems like it should be the variable schema, like so

"SELECT "+cols+", "+hcols+" FROM "+schema+"."+table+" "

instead of 

"SELECT "+cols+", "+hcols+" FROM epanet."+table+" "

Thanks

**Comment by vmora** [comment]
Hi, thanks for reporting and finding the bug. 

Would you mind submitting a PR ?

**Comment by eg-novelt** [comment]
PR created:

https://github.com/Oslandia/qgis-versioning/pull/46

Merci pour la réponse rapide

**Comment by eg-novelt** [comment]
This has been fixed by the PR
