### ISSUE TITLE
Uncaught AssertionError

### ISSUE THREAD

**Issue by simbamangu** [Oslandia/qgis-versioning#47]
Steps to reproduce
1. Add PostGIS layer to group; 
2. Select 'versioning' tool 
3. Confirm that '4 fields will be added ...'

Fails with the below error on Mac OS X 10.10.5, QGIS 2.14. 

Also fails on Linux 16.04, QGIS 2.16. 

```
Traceback (most recent call last):
  File "/Users/simbamangu/.qgis2/python/plugins/qgis_versioning/versioning.py", line 616, in historize
    versioning_base.historize( self.pg_conn_info(), schema )
  File "/Users/simbamangu/.qgis2/python/plugins/qgis_versioning/versioning.py", line 110, in pg_conn_info
    assert(False) # TODO request connection
AssertionError

```

qgis_versioning 0.4, QGIS 2.14.3-Essen on Darwin 14.5.0

**Comment by vmora** [comment]
The plugin tries to guess the connection to posgresql, but fails because there are several postgresql databases in the project. 

Can you confirm and change the title to "Add support for project with heterogeneous posgresql sources" ?

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
