### ISSUE TITLE
Spatialite Checkout error

### ISSUE THREAD

**Issue by Sameme** [Oslandia/qgis-versioning#49]
Spatialite checkout is not working with the plugin. Coming up with this python error

"2016-10-05T19:58:30    1   Traceback (most recent call last):
              File "C:/Users/eHA-Samuel/.qgis2/python/plugins\qgis_versioning\versioning.py", line 692, in checkout
                tables_for_conninfo, filename, user_selected_features )
              File "C:/Users/eHA-Samuel/.qgis2/python/plugins\qgis_versioning\versioning_base.py", line 362, in checkout
                "AND "+branch+"_rev_begin IS NOT NULL")
              File "C:/Users/eHA-Samuel/.qgis2/python/plugins\qgis_versioning\versioning_base.py", line 123, in execute
                self.cur.execute( sql )
            OperationalError: near "FROM": syntax error"

I have also attached a screenshot of this error with this issue.
@vmora 

![versioning_error](https://cloud.githubusercontent.com/assets/12427102/19127536/4c3235b0-8b37-11e6-9084-e008a7b9976f.JPG)

**Comment by vmora** [comment]
The line 123 in master reads:
```
            self.log = codecs.open( filename, 'w', 'utf-8' )
```

So I would need the release version you are using.

**Comment by Sameme** [comment]
This the version i have on my system
Installed version: 0.4

I guess this is the only available version on the QGIS Repo or Can one chose version?

**Comment by guyschvitz** [comment]
I have the same issue! Also using version 0.4. QGIS reports this error and then stores a SpatiaLite file that fails to load.

**Comment by vmora** [comment]
Maybe the same problem, with solution here: https://github.com/GISeHealth/qgis-versioning/issues/38

**Comment by vmora** [comment]
@Sameme, @guyschvitz can you confirm that the proposed solution works and close ?

If you need support for spaces in path, then open another issue with that in the name.
