### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'source'


### ISSUE THREAD

**Issue by peter-shr** [Oslandia/qgis-versioning#51]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/user/.qgis2/python/plugins\qgis_versioning\versioning.py", line 187, in on_legend_click
    uri = QgsDataSourceURI(layer.source())
AttributeError: 'NoneType' object has no attribute 'source'

```
qgis_versioning 0.4, QGIS 2.14.8-Essen on Windows 10

**Comment by ar-jan** [comment]
I get a similar probem (Windows 7, QGIS 2.18.5, qgis-versioning 0.6, PostgreSQL 9.6, PostGIS 2.3). Same cause? Any clues what's wrong?

> Traceback (most recent call last):
>   File "C:/Users/arjan/.qgis2/python/plugins\qgis_versioning\versioning.py", line 848, in historize
>     versioning_base.historize( self.pg_conn_info(), schema )
>   File "C:/Users/arjan/.qgis2/python/plugins\qgis_versioning\versioning.py", line 189, in pg_conn_info
>     if layer.providerType() == "postgres":
> AttributeError: 'TileLayer' object has no attribute 'providerType'

**Comment by gignacnic** [comment]
What type of layers you have in the group layer in QGIS you are versioning (printscreen)? It seems that you have combined in the group, layers that are not postgres and it seems to be either a: TileLayer (https://github.com/Oslandia/qgis-versioning/issues/51#issuecomment-291540352) or a source that did not open successfully (https://github.com/Oslandia/qgis-versioning/issues/51#issue-190642727)...

**Comment by ar-jan** [comment]
Hmm, interesting. So I had created a normal group in the Layers Panel (Add Group), then added just one PostGIS layer to this group.

I now created a new project and did the same thing, and the "historize" action worked correctly. The only difference is that in my earlier project, there were also other groups with layers in them when I first tried, but I had selected the one with only the PostGIS layer.

I'll see if I can get it to work in the existing project as well. Thanks!

**Comment by gignacnic** [comment]
Yes, you need to have a group layer that includes only the layers that you want to "historize" in PG.

**Comment by ar-jan** [comment]
But is it expected that there can be *no other* groups in the project? I thought that the historize action would act on just the selected group, so it shouldn't matter that there are also other groups.

**Comment by ar-jan** [comment]
Just tried it again in a new project, and it seems that currently the only way historize a group is to have *no other groups with layers present anywhere in the QGIS project*. There can only be one group with the PostGIS layer to be versioned, or I get `AttributeError: 'TileLayer' object has no attribute 'providerType'`.

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
