### ISSUE TITLE
Spatialite checkout needs to be upgraded to work perfectly on higher version of QGIS ex. QGIS 2.14

### ISSUE THREAD

**Issue by Sameme** [Oslandia/qgis-versioning#56]
Using the spatialiet checkout of the plugin only works perfectly with QGIS 2.8, once you start using it with higher QGIS version, it starts coming up with various errors and issues.

Find error screenshots below
![picture1](https://cloud.githubusercontent.com/assets/12427102/24523561/5a3c1980-158b-11e7-967f-0da609f73c00.png)  
![picture2](https://cloud.githubusercontent.com/assets/12427102/24523573/61f1efec-158b-11e7-93f0-a257f5365e73.png)
![picture3](https://cloud.githubusercontent.com/assets/12427102/24523578/66004250-158b-11e7-8e4e-f85b8790d5bf.png)

**Comment by vmora** [comment]
Can you tell me the version of gdal (ogr2ogr), the version of spatialite and the version of qgis you are using ?

**Comment by Sameme** [comment]
I used QGIS 2.14.12, gdal/ogr version 2.1.3 and spatialite Version 4.3.0.

**Comment by gignacnic** [comment]
I supposed this kind of test will be easier to do when the Travis-CI QA will be fully integrated in the process?

**Comment by vmora** [comment]
@gignacnic I have made some progresses on the travis front too, the problem now is that the pyspatialite module cannot be found (although it's installed) see #57 for details of travis failures.

Also the units tests can now be run from the qgis python console:
```python
from qgis_versioning.test import test
test()
```

**Comment by gignacnic** [comment]
This problem is related to checkout without selecting any features in the table in QGIS before checking out. Once you select any element in QGIS before doing a checkout it works as expected with QGIS 2.18. So we need to look at the command that is executing a checkout with selection to fix the problem.

**Comment by vmora** [comment]
@Sameme can you confirm it's fixed by #57 (the last zip I sent you) such that I can merge and close ?
