### ISSUE TITLE
Error when creating a branch:  "no password supplied"

### ISSUE THREAD

**Issue by samson8720** [Oslandia/qgis-versioning#58]
Software:  QGIS 2.18 and versioning plugin obtained through QGIS

After creating a versioned group I attempted to create a branch.  The following error results:
--------------------------------------------------------------------------------------------------------
2017-03-31T11:44:58	1	Traceback (most recent call last):
			  File "C:/Users/geoproject/.qgis2/python/plugins\qgis_versioning\versioning.py", line 488, in branch
			    schema, branch, commit_msg, base_branch, base_rev )
			  File "C:/Users/geoproject/.qgis2/python/plugins\qgis_versioning\versioning_base.py", line 1030, in add_branch
			    pcur = Db(psycopg2.connect(pg_conn_info))
			OperationalError: fe_sendauth: no password supplied
-------------------------------------------------------------------------------------------------------
Any help would be greatly appreciated

**Comment by gignacnic** [comment]
It looks that your connection to DB is still not active in your project. You can do that by choosing to save user and password while establishing the PostGIS connection: https://i.stack.imgur.com/jJB8v.png

**Comment by samson8720** [comment]
Thank you for the quick reply.  I had the same thought about saving the username and password in the connection.  Still received the same error message.  I might mention I am using Windows 7.

**Comment by samson8720** [comment]
Like many steps with QGIS-PostGIS, I failed to refresh connections before attempting to create a branch.
