### ISSUE TITLE
SL filter (subset) checkout only checkout polygon layer and not point layer

### ISSUE THREAD

**Issue by Sameme** [Oslandia/qgis-versioning#61]
My initial testing from last night shows great improvement using it with QGIS 2.18, the issue I noticed is that while trying to create a filtered (subset) checkout only the polygon layers subset could be checked out. The point filtered (subset) geometry and attribute wasn't included, just the layer name.

But when I tried checkout out my whole database without any filter, all layers including polygon and point checkout out, but once I introduce filter, only the point layer name is included in my checkout without geometry and table.

Also the information GUI that normally alert you on the number of subset you are filtering out display appropriately, telling me that I am checkout out this number of point data but once the checkout is completed, I see only the layer name without data; geometry and table.

In addition, I just noticed the string abbreviation bug is still on but this time on newly inserted record. This happens on fields with string or text data type

Please see attachment

![string issue](https://cloud.githubusercontent.com/assets/12427102/24791967/0d3fee88-1b74-11e7-94ad-da898381222d.JPG)

This is the screenshot of the working copy layer where the feature was created and committed to the master
![scrren](https://cloud.githubusercontent.com/assets/12427102/24792117/99ec03f8-1b74-11e7-8049-e91585a97f52.JPG)

**Comment by vmora** [comment]
Thanks to your data, I'm now able to reproduce.

I should be able to fix that on Monday morning, for the moment what I see is that the temporary view is correctly created and that the data must be lost in the transfer to spatialite.

**Comment by vmora** [comment]
@Sameme, fixed, You'll find a fixed version at the same place for testing.
