### ISSUE TITLE
Corrupted Versioned Layers When Reloading

### ISSUE THREAD

**Issue by samson8720** [Oslandia/qgis-versioning#62]
QGIS 2.18.5  | Versioning plugin 0.6 |  Windows 7

After creating a version from a group layer (point, line and polygon layers), and then clearing QGIS of the project, an error occurs when reloading the views for the point and line layers.  The polygon layer reloads without a problem (the metadata window is populated).  The "properties" for the point and line layers shows the word "error" in the metadata window.  I have closed QGIS, re-establish a connection to the database with the same errors with the point and line layers remain.  Any thoughts as to why the problems occur with point and line layers?

Thanks for your assistance.

**Comment by vmora** [comment]
Can you reproduce with the latest version I sent: there was a major issue with partial checkout (wrong features ids), that may be the source of this problem.

If it's not the case, I'll definitely need a precise procedure to reproduce the problem.

**Comment by samson8720** [comment]
During this past weekend I discovered the problem to my posted issue.  Although an "id" field was identified as the primary key when importing a shapefile with DB Manager, this information was not saved in the PostGIS database.  Adding the PostGIS layers (after importing the shapefiles) with Layer --> Add Layer --> Add PostGIS Layers, the problem was identified.
![Uploading samson.jpg…]()

**Comment by samson8720** [comment]
During this past weekend I discovered the problem to my posted issue.  Although an "id" field was identified as the primary key when importing a shapefile with DB Manager, this information was not saved in the PostGIS database.  Adding the PostGIS layers (after importing the shapefiles) with Layer --> Add Layer --> Add PostGIS Layers, the problem was identified.
![Uploading samson.png…]()

**Comment by samson8720** [comment]
During this past weekend I discovered the problem to my posted issue. Although an "id" field was identified as the primary key when importing a shapefile with DB Manager, this information was not saved in the PostGIS database. Adding the PostGIS layers (after importing the shapefiles) with Layer --> Add Layer --> Add PostGIS Layers, the problem was identified.

![Uploading samson.png…]()

**Comment by samson8720** [comment]
During this past weekend I discovered the problem to my posted issue. Although an "id" field was identified as the primary key when importing a shapefile with DB Manager, this information was not saved in the PostGIS database. Adding the PostGIS layers (after importing the shapefiles) with Layer --> Add Layer --> Add PostGIS Layers, the problem was identified.   The "Feature ID" for each layer was not selected.  Every time the versioned layers are added to QGIS the Feature ID must be selected.

**Comment by gignacnic** [comment]
I think it is a related to a well known problem in QGIS with primary key (id) and PG views, not the plugin: https://lists.osgeo.org/pipermail/qgis-user/2015-August/033083.html
https://hub.qgis.org/issues/11317

**Comment by samson8720** [comment]
Thanks!  I appreciate the explanation for the issue I am having.

Scott A. Samson, Extension Professor
Geosystems Research Institute
Mississippi State University
Research Blvd 2
Mississippi State, MS 39762
Email:  ssamson@gri.msstate.edu<mailto:ssamson@gri.msstate.edu>
Ph:  662-769-1654
