### ISSUE TITLE
PostGIS checkout: Filter (subset) of DB needs to be enabled

### ISSUE THREAD

**Issue by Sameme** [Oslandia/qgis-versioning#63]
@vmora  Currently to filter and checkout a subset of your database is only possible with the spatialite checkout. This functionality needs to be made possible on the PostGIS view checkout as well.

**Comment by gignacnic** [comment]
This functionality can be develop as it was for the SL file, as creating a temp checkout view with filter using ogr2ogr and create it in the new checkout schema.

**Comment by vmora** [comment]
@gignacnic actually it's even simpler because the postgis checkout is already a view, we only need to add a condition (id in) to the view defiinition.
