### ISSUE TITLE
foreign key violates and error in PG for SL checkout

### ISSUE THREAD

**Issue by gignacnic** [Oslandia/qgis-versioning#66]
When doing a checkout in SpatiaLite format, views created is where the editing should occur. However, if by mistake any users edits (ex. delete, insert, etc.) in the SL tables instead of the view, it creates IntegrityError in PG later and could not commit. In checkout, no contraint (ex. foreign key : trunk_child, trunk_parent) presents in the PG tables are created in SL tables. The behaviour should be the same as SL checkout and PG checkout at the table levels with contraints, this will prevent user to delete or insert records (related to foreign keys) in SL that could not be committed back to PG.

See the details of the error of @Sameme, when trying to commit:

qgis_versioning\versioning.py", line 171, in execute
raise e
IntegrityError: insert or update on table "table_name" violates foreign key constraint "table_name_trunk_child_fkey"
DETAIL: Key (trunk_child)=(320) is not present in table "table_name".

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
