### ISSUE TITLE
Recognize if a schema is versioned + option to historize new tables in versioned schema

### ISSUE THREAD

**Issue by kadarivan** [Oslandia/qgis-versioning#67]
If I add a versioned table (not a branch view) to a group, the "historize" button is enabled (#20).
Now very difficult to historize a new table in a versioned schema. I must add the 4 columns to the table and create view in the branch schema. It should be automated.

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
