### ISSUE TITLE
gid should be the first column in views (not geom)

### ISSUE THREAD

**Issue by kadarivan** [Oslandia/qgis-versioning#68]
QGIS failed to recognise the private key of view if the geom is the first column. So I can't add layer from QGIS Browser or DB Manager.
(I can add the layer with Add PostGIS Layers button, but in this case, I must select the private key every time manually)

**Comment by gignacnic** [comment]
This is QGIS limitation, but not related to the plugin. What you can do and I have done it and test it successfully, it is to update in PgAdmin this view by reordering fields in the SELECT.
You just have to update by replacing the view created by the plugin in the trunk schema and reorder default fields and placing unique_id as the first column:
CREATE OR REPLACE VIEW trunk_rev_head.view_name WITH (security_barrier=true) AS 
SELECT table_name.name_of_your_unique_id_field, table_name.geom, ....

**Comment by kadarivan** [comment]
Thanks, i did it. But it means, that I must do it with all my colleges' PGcheckout shemas.
I hoped, it could be changed in the plugin. The plugin should not reverse the columns order, when historize the schema, creating the rev_head or new PGcheckout...

**Comment by gignacnic** [comment]
You do not have to do it for all PG checkout. Once it is done in the trunk schema, every time someone will do a PG checkout afterward, it will use columns order from the trunk view in the checkout.

**Comment by kadarivan** [comment]
For me, the checkout reverse the columns order (QGIS 2.14.15 LTR, versioning 0.8, PG 9.6, PGIS 2.3.2)

And the CREATE OR REPLACE VIEW... is not working, I must delete the views first: https://www.postgresql.org/docs/9.6/static/sql-createview.html

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
