### ISSUE TITLE
postgres local checkout from remote prostgres

### ISSUE THREAD

**Issue by andrei4002** [Oslandia/qgis-versioning#7]
is it possible to checkout from a remote postgres schema, to a local working postgres schema ?

**Comment by vmora** [comment]
I don't think so because the code uses the same connection info for the checkout.

**Comment by vmora** [comment]
This is related to #47

**Comment by ar-jan** [comment]
It would be a great feature to have on the roadmap. For example, the local PostgreSQL server might be more powerful. Or for when you need to take a laptop into the field.

**Comment by gignacnic** [comment]
If you do want to have a local PostgreSQL on a laptop that you want to bring into the field, it can be done by going into this workaround after doing a PG checkout on the main source DB:
1- Dump the 3 schemas (schema source, schema truck, schema just been checkout);
2- Restore of dump 1) into another local instance PG (laptop yo bring to the field)
3- Modified this local PG checkout data with QGIS versioning plugin in QGIS (on your laptop)
4- Dump only one schema checkout that has been modified in 3) (on your laptop)
5- Restore only the schema dump checkout in 4) in the main intial PG source DB
6- Commit changes of this new restore checkout into the trunk in QGIS with the plugin

**Comment by ar-jan** [comment]
Thanks for describing these steps @gignacnic!

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
