### ISSUE TITLE
Add geometry in QGIS conflict layer

### ISSUE THREAD

**Issue by troopa81** [Oslandia/qgis-versioning#86]

**Comment by troopa81** [comment]
@vmora Not sure what has to be done, It seems to work for me.

I modify a point in two spatialite working copies, commit one and then when I update the other working copy, I have a conflict layer with my two points.

What am I missing?

**Comment by vmora** [comment]
Well, it works as it's supposed to work (I designed it that way ;) 

You'll have to setup a zoom meeting with Samuel to understand what the problem is.

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
